
     ccccaaaattttcccchhhh((((3333))))               MMMMuuuuddddOOOOSSSS ((((5555 SSSSeeeepppp 1111999999994444))))                ccccaaaattttcccchhhh((((3333))))

     NNNNAAAAMMMMEEEE
          catch() - catch an evaluation error

     SSSSYYYYNNNNOOOOPPPPSSSSIIIISSSS
          mixed catch( mixed expr );

     DDDDEEEESSSSCCCCRRRRIIIIPPPPTTTTIIIIOOOONNNN
          Evaluate <expr>. If there is no error, 0 is returned. If
          there is a standard error, a string (with a leading '*')
          will be returned.

          The function throw() can also be used to immediately return
          any value, except 0. catch() is not really a function call,
          but a directive to the compiler.

          The catch() is somewhat costly, and should not be used just
          anywhere.  Rather, use it at places where an error would
          destroy consistency.

     SSSSEEEEEEEE AAAALLLLSSSSOOOO
          error(3), throw(3), error_handler(4)

     Page 1                                          (printed 3/16/95)

